apiVersion: v1
data:
  application.instanceLabelKey: ""
  configManagementPlugins: ""
  dex.config: ""
  ga.anonymizeusers: "false"
  ga.trackingid: ""
  help.chatText: ""
  help.chatUrl: ""
  kustomize.buildOptions: ""
  repositories: |
    - type: git
      url: https://github.com/argoproj/argocd-example-apps.git
    - type: git
      url: https://github.com/uS-aito/testRepo.git
    - type: git
      url: https://github.com/uS-aito/first-N-digit-prime-in-pi.git
  repository.credentials: ""
  resource.exclusions: ""
  resource.inclusions: ""
  statusbadge.enabled: "false"
  url: https://example-argocd-server
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    example: basic
  name: argocd-cm
  namespace: argocd
